import argparse
import json
from pathlib import Path
from typing import Any, Dict, Iterable, Tuple

from crypto_analyzer.volatility_analysis import (
    detect_volatility_expansion_signals,
    format_volatility_analysis,
)


def load_json(path: Path) -> Dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"File not found: {path}")
    with path.open("r", encoding="utf-8") as fp:
        return json.load(fp)


def latest_kline(klines: Iterable[Dict[str, Any]]) -> Dict[str, Any]:
    klines = list(klines)
    if not klines:
        raise ValueError("No kline data found in JSON")
    return klines[-1]


def order_book_imbalance(order_book: Dict[str, Any], depth: int = 10) -> float:
    bids = order_book.get("bids") or []
    asks = order_book.get("asks") or []
    bid_value = sum(float(price) * float(qty) for price, qty in bids[:depth])
    ask_value = sum(float(price) * float(qty) for price, qty in asks[:depth])
    total = bid_value + ask_value
    return (bid_value - ask_value) / total if total else 0.0


def summarize(payload: Dict[str, Any]) -> Dict[str, Any]:
    last = latest_kline(payload.get("klines", []))
    ticker = payload.get("ticker_24hr", {})
    funding = payload.get("funding_rate", {})
    open_interest = payload.get("open_interest", {})
    order_book = payload.get("order_book", {})
    current_price_data = payload.get("current_price", {})

    # 优先使用实时价格，如果没有则使用最后一根K线的收盘价
    price = current_price_data.get("price")
    if price is None:
        price = float(last.get("close", 0))

    summary = {
        "symbol": last.get("symbol") or ticker.get("symbol") or current_price_data.get("symbol") or payload.get("exchange", "unknown"),
        "current_price": price,  # 实时价格或K线收盘价
        "kline_close": float(last.get("close", 0)),  # K线收盘价（用于对比）
        "ma20": last.get("ma20"),
        "ma50": last.get("ma50"),
        "rsi14": last.get("rsi14"),
        "change_24h_pct": ticker.get("priceChangePercent"),
        "funding_rate": funding.get("lastFundingRate") or funding.get("fundingRate"),
        "open_interest": open_interest.get("openInterest"),
        "order_book_imbalance": order_book_imbalance(order_book),
    }
    return summary


def format_summary(summary: Dict[str, Any]) -> str:
    lines = [
        f"Symbol: {summary['symbol']}",
        f"Current Price: {summary.get('current_price', 0)}",
    ]
    # 如果实时价格和K线收盘价不同，显示K线收盘价作为参考
    if summary.get('kline_close') and abs(summary.get('current_price', 0) - summary.get('kline_close', 0)) > 0.0001:
        lines.append(f"K-line Close: {summary.get('kline_close')}")
    lines.extend([
        f"MA20 / MA50: {summary.get('ma20')} / {summary.get('ma50')}",
        f"RSI14: {summary.get('rsi14')}",
        f"24h Change %: {summary.get('change_24h_pct')}",
        f"Funding Rate: {summary.get('funding_rate')}",
        f"Open Interest: {summary.get('open_interest')}",
        f"Order Book Imbalance (10 levels): {summary.get('order_book_imbalance')}",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Summarize a JSON file generated by scripts/crypto_fetcher.py."
    )
    parser.add_argument("--file", required=True, help="Path to the JSON file to summarize")
    args = parser.parse_args()
    path = Path(args.file)
    data = load_json(path)
    summary = summarize(data)
    print(format_summary(summary))
    
    # 始终包含波动率分析
    print("\n")
    vol_result = detect_volatility_expansion_signals(
        klines=data.get("klines", []),
        ticker_24hr=data.get("ticker_24hr"),
        funding_rate=data.get("funding_rate"),
        open_interest=data.get("open_interest"),
        order_book=data.get("order_book")
    )
    print(format_volatility_analysis(vol_result))


if __name__ == "__main__":
    main()

